In [83]:
import numpy as np

In [84]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]


In [85]:
arr=np.array(list) 

In [86]:
print (arr *4)

[ 80 108  36  48 124  68  16 200 156 140]


In [87]:
print (np.mean(arr))

24.4


In [88]:
print (np.median(arr))


23.5


In [89]:
print(np.std(arr))


13.828955130450023


In [90]:
min_index = np.argmin(arr)
max_index = np.argmax(arr)

In [91]:
print (min_index)
print(max_index)

6
7


In [92]:
print (arr[min_index])
print (arr[max_index])

4
50


In [93]:
print (np.min(arr))
print(np.max(arr))


4
50


In [94]:
greater_than_20 = arr[arr >20]
print (greater_than_20)

[27 31 50 39 35]


In [95]:
matrix = np.array ([[5,12,17,9],[8,21,14,3],[6,13,19,11]])

In [96]:
print (matrix.shape)
print (matrix.shape[0])
print (matrix.shape[1])

(3, 4)
3
4


In [97]:
print (matrix[1])
print (matrix *2)
print (np.mean(matrix, axis=0))
print (np.mean(matrix))
print (np.max(matrix, axis=1))
print (np.min(matrix,axis=0))


[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]


In [98]:
flat = matrix.flatten()
print (flat)
print (flat.shape)


[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)


In [99]:
min_index = np.argmin(matrix)
max_index= np.argmax(matrix)
print (min_index)
print(max_index)


7
5


In [100]:
min_coords = np.unravel_index(min_index, matrix.shape)
max_coords = np.unravel_index (max_index, matrix.shape)
print (min_coords)
print(max_coords)


(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))


In [101]:
greater_than_15 = matrix[matrix > 15]
print (greater_than_15)

[17 21 19]


In [102]:
sorted_row = np.sort(matrix, axis=1)
print(sorted_row)

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [103]:
arr = np.array([[2,3,5],[14,6,8],[11,13,17],[7,10,13]])


In [104]:
def is_prime(n):
    if n <2:
        return False
    for i in range (2,n):
        if n % i == 0:
            return False 
    return True 

In [105]:
def rows_with_prime(arr):
    result = []

    for row in arr:
        for value in row:
            if is_prime(value):
                result.append(row)
                break
    return np.array(result)
print (rows_with_prime(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [106]:
def checkerboard():
    board = np.zeros((8,8), dtype=int)

    for i in range(8):
        for j in range (8):
            if (i+j) % 2 ==0:
                board[i][j]=1
    return board
def reverse_checkerboard(): 
    board = np.zeros((8,8), dtype=int)

    for i in range(8):
        for j in range (8):
            if (i+j) %2 == 1:
                board [i][j]=1
    return board 

print (checkerboard())
print ()
print (reverse_checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [107]:
def expansion(arr, spaces): 
    result = []

    for word in arr: 
        result.append((" "*spaces).join(word))

    return np.array(result)

universe= np.array(['galaxy','clusters'])

print(expansion(universe,1))
print(expansion(universe,2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [108]:
def secondDimmest(stars): 
    result = []

    for row in stars: 
        sorted_row = np.sort(row)
        result.append(sorted_row[-2])

    return np.array(result)

np.random.seed(123)
stars = np.random.randint(500,2000,(5,5))

print (stars)
print (secondDimmest(stars))
    

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
